name: Generate Vue Coding Challenge

on: push

jobs:
  generate-challenge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check network connectivity
        run: ping -c 5 github.com

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: python -m pip install

      - name: Generate Challenge
        id: generate_challenge
        run: |
          # Script to generate a random Vue coding challenge
          challenge_title="Vue Coding Challenge: Implement a simple todo list app"
          challenge_description="Create a Vue.js application that allows users to add, edit, and delete todo items. The app should have a form to add new todo items, a list to display existing todo items, and options to edit or delete each item."
          echo "Challenge Title: $challenge_title" > challenge.txt
          echo "Challenge Description: $challenge_description" >> challenge.txt

      - name: Create Issue
        uses: peter-evans/create-issue-from-file@v2
        with:
          title: New Vue Coding Challenge
          content-filepath: challenge.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
