name: Generate Random Vue Coding Challenge

on: push

jobs:
  generate-challenge:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Challenge
        id: fetch_challenge
        run: |
          challenge_data=$(curl -s https://example.com/api/random-vue-challenge)
          challenge_title=$(echo "$challenge_data" | jq -r '.title')
          challenge_description=$(echo "$challenge_data" | jq -r '.description')
          echo "::set-output name=title::$challenge_title"
          echo "::set-output name=description::$challenge_description"

      - name: Create Issue
        run: |
          headers="-H 'Authorization: token ${{ secrets.YOUR_GITHUB_TOKEN }}' -H 'Accept: application/vnd.github.v3+json'"
          body="-d '{\"title\":\"${{ steps.fetch_challenge.outputs.title }}\",\"body\":\"${{ steps.fetch_challenge.outputs.description }}\"}'"
          url="https://api.github.com/repos/${{ github.repository }}/issues"
          curl -X POST $headers $body $url
